### ISSUE TITLE
:/

### ISSUE THREAD

**Issue by JohnMcLear** [filmaj/cordova-appium#1]
https://github.com/filmaj/cordova-appium/blob/bef0beb468f80056166a6b5c42ec178e427ad96f/test/ios-geolocation.js#L24

**Comment by filmaj** [comment]
yeah that'd be a problem eh?

what's the solution? point out in the readme to customize the (selenium) desired capabilities?

**Comment by JohnMcLear** [comment]
tbh idk this project is completely broken so I don't really think it's worth fixing?  Perhaps just flag the project as abandoned?

**Comment by filmaj** [comment]
haha, oof, ok, ouch, but I hear you. I also have a wider set of appium tests in a repo for different kinds of android/ios apps (hybrid, native, different types of browser-on-mobile tests) over here: https://github.com/filmaj/appium-test

In the mean time I will do what you suggest and delete this repo.
